### ISSUE TITLE
载入插件错误：chat

### ISSUE THREAD

**Issue by zCN24** [ikechan8370/chatgpt-plugin#38]
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'puppeteer-extra-plugin-stealth' imported from C:\Users\Administrator\Desktop\Yunzai-Bot\plugins\chatgpt-plugin\utils\browser.js
0|Yunzai-Bot  | Did you mean to import puppeteer-extra-plugin-stealth@2.11.1_puppeteer-extra@3.3.4/node_modules/puppeteer-extra-plugin-stealth/index.js?
0|Yunzai-Bot  |     at new NodeError (node:internal/errors:387:5)
0|Yunzai-Bot  |     at packageResolve (node:internal/modules/esm/resolve:951:9)
0|Yunzai-Bot  |     at moduleResolve (node:internal/modules/esm/resolve:1000:20)
0|Yunzai-Bot  |     at defaultResolve (node:internal/modules/esm/resolve:1214:11)
0|Yunzai-Bot  |     at nextResolve (node:internal/modules/esm/loader:165:28)
0|Yunzai-Bot  |     at ESMLoader.resolve (node:internal/modules/esm/loader:844:30)
0|Yunzai-Bot  |     at ESMLoader.getModuleJob (node:internal/modules/esm/loader:431:18)
0|Yunzai-Bot  |     at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
0|Yunzai-Bot  |     at link (node:internal/modules/esm/module_job:75:36) {
0|Yunzai-Bot  |   code: 'ERR_MODULE_NOT_FOUND'
0|Yunzai-Bot  | }

**Comment by hydeng2022** [comment]
我这个也是chat加载失败，但是后面报错内容不一样，安装依赖的时候也有好多警告
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'p
uppeteer-extra-plugin-stealth' imported from C:\Users\Administrator\Desktop\Yunz
ai-Bot\plugins\chatgpt-plugin\utils\browser.js
    at new NodeError (node:internal/errors:371:5)
    at packageResolve (node:internal/modules/esm/resolve:851:9)
    at moduleResolve (node:internal/modules/esm/resolve:896:18)
    at defaultResolve (node:internal/modules/esm/resolve:1011:11)
    at ESMLoader.resolve (node:internal/modules/esm/loader:422:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:222:40)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
    at link (node:internal/modules/esm/module_job:75:36) {
  code: 'ERR_MODULE_NOT_FOUND'

**Comment by yyk725** [comment]
readme看一下，需要装新的依赖puppeteer-extra-plugin-stealth
![image](https://user-images.githubusercontent.com/72236930/207382075-3af240d0-a9d1-4038-9650-40a9fbe24399.png)

**Comment by zCN24** [comment]
> 
安装报错

**Comment by yyk725** [comment]
报错截个图，应该能处理的

**Comment by zCN24** [comment]
> 报错截个图，应该能处理的

插件加载成功了，但是出现新报错https://github.com/ikechan8370/chatgpt-plugin/issues/46

**Comment by hydeng2022** [comment]
> 报错截个图，应该能处理的

$ pnpm install -w chatgpt undici showdown mathjax-node puppeteer-extra puppeteer-extra-plugin-stealth
Progress: resolved 0, reused 1, downloaded 0, added 0
Progress: resolved 224, reused 220, downloaded 0, added 0
 WARN  deprecated left-pad@1.3.0: use String.prototype.padStart()
 WARN  deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
 WARN  deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
 WARN  deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
 WARN  deprecated har-validator@5.1.5: this library is no longer supported
Progress: resolved 677, reused 676, downloaded 0, added 0
Already up to date

Done in 3s

**Comment by yyk725** [comment]
> 

这就是可以了，看到Already up to date说明pnpm install -w后面的插件都装好了
